### ISSUE TITLE
Include an example in readme how to pass existing UUID instead of auto-generation.

### ISSUE THREAD

**Issue by ivictbor** [odo-network/sequelize-binary-uuid#1]
Hi Braden and thanks a lot for sharing this! I've seen your discussion in https://github.com/sequelize/sequelize/issues/9271 and looks like you know how to achieve best results from using uuids AS primary keys.

Basically we want to generate `uuids/v1` identifiers on frontend and send it to server, the main reason is to  allow much more responsive UX of frontend.

1. I am interested should I pass it as 

```
const uuidv1 = require('uuid/v1');
const uuid = uuidv1(); 
```

```
User.create({ id:  uuid}),
```
or 

```
 User.create({ uuid:  uuid}),
```
I have 
```
'ERROR:Error calling proxy "signup": SequelizeDatabaseError: Data too long for column \'id\' at row 1 '
```
in both cases though in db it was created correctly

![image](https://user-images.githubusercontent.com/1838656/62304292-5a976780-b486-11e9-90cd-835f6de56480.png)

2. Is this package uses `BIN_TO_UUID` and `UUID_TO_BIN` native mysql 8.0+ functions? If yes then lets state it in readme (I can create PR)

2. I haven't not took full look on sources yet, but did you implement function to rearrange UUIDs from this post in the library? https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/

```
123456 | DELIMITER //CREATE DEFINER=`root`@`localhost` FUNCTION `ordered_uuid`(uuid BINARY(36)) RETURNS binary(16) DETERMINISTIC RETURN UNHEX(CONCAT(SUBSTR(uuid, 15, 4),SUBSTR(uuid, 10, 4),SUBSTR(uuid, 1, 8),SUBSTR(uuid, 20, 4),SUBSTR(uuid, 25)));//DELIMITER ;
-- | --
```

**Comment by bradennapier** [comment]
No, I rewrote it to work with any version of mysql so it does it all locally including the re-arrangement without requiring access to the MySql v8 functionality.

It actually turned out to be really simple in the end.  You can see the actual UUID work in the other package that this package uses: https://github.com/odo-network/binary-uuid/blob/master/src/binary-uuid.js

I re-arrange the UUID to be consistent with the mysql recommended practices which, yes, came from the article you posted I believe.  I read that one as well while designing it and they were the same thing.

In the end, it seems you can just use this package to get exactly what you are wanting! 

I do not have sql do any of the work.  I just use `node` and buffer to re-arrange it as defined by the spec so that the uuid is available on creation rather than needing to create the value in sql then re-capture it which is not a simple task when adding a new value to the table.

You can see the package is re-arranging by just looking at the byte ordering of the example:

```js
sequelize
  .sync({ force: true })
  .then(() =>
    Promise.all([
      User.create({ someKey: "one" }),
      User.create({ someKey: "two" }),
      User.create({ someKey: "three" })
    ])
  )
  .then(() => User.findAll())
  .then(users => users.map(user => user.get({ plain: true })))
  .then(console.log);
```

```js
[
  {
    uuid: '8cde7820-04c1-11e9-8d40-0d6e8c185c6c',
    id: <Buffer 11 e9 04 c1 8c de 78 20 8d 40 0d 6e 8c 18 5c 6c>,
    someKey: 'one',
    createdAt: 2018-12-21T01:41:35.000Z,
    updatedAt: 2018-12-21T01:41:35.000Z
  },
  {
    uuid: '8cdec640-04c1-11e9-8d40-0d6e8c185c6c',
    id: <Buffer 11 e9 04 c1 8c de c6 40 8d 40 0d 6e 8c 18 5c 6c>,
    someKey: 'two',
    createdAt: 2018-12-21T01:41:35.000Z,
    updatedAt: 2018-12-21T01:41:35.000Z
  },
  {
    uuid: '8cdec641-04c1-11e9-8d40-0d6e8c185c6c',
    id: <Buffer 11 e9 04 c1 8c de c6 41 8d 40 0d 6e 8c 18 5c 6c>,
    someKey: 'three',
    createdAt: 2018-12-21T01:41:35.000Z,
    updatedAt: 2018-12-21T01:41:35.000Z
  }
]
```

Even though they are created in the same fn you will notice that `one`, `two`, and `three` are byte-ordered so that they will be organized in-order.

1. 11 e9 04 c1 8c de **78** 20 8d 
2. 11 e9 04 c1 8c de c6 **40** 8d
3. 11 e9 04 c1 8c de c6 **41** 8d

---

**Update**

Upon review, it appears I actually link the article you asked about in the readme for the included package which actually works on the `uuid` https://github.com/odo-network/binary-uuid

**Comment by bradennapier** [comment]
Oh yeah, and the `binary-uuid` package linked is pretty much an example of how to do it yourself ;-) its all only a few lines of code.

**Comment by ivictbor** [comment]
thanks for explanation! @bradennapier
